typography_spectrum: 0.16957991663366556
color:
  brandStrength: 0.6159698329865932
  lightness: 0.9279972049407661
  saturation: 0.8972105965949595
  rhythmicContrast: 0.7990278007928282
  brandColors:
    - '#F2385A'
    - '#F5A503'
    - '#E9F1DF'
    - '#4AD9D9'
    - '#36B1BF'
layout_spectrum: 0.9168107116129249
author:
  name: ''
  email: kevin@timelessmomentsvideo.com
  url: 'https://thegrid.ai/timeless-moments/'
name: Timeless Moments Video
title: >-
  Timeless Moments Video-- You've seen the ordinary.  Come experience the
  extraordinary.
